=== EuPathDB-Infra/ApiCommonWebsite/Model/lib/rng/projects.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.eupathdb.org"
  xmlns:tns="http://www.eupathdb.org" elementFormDefault="qualified">

  <element name="projects" type="tns:projects"></element>

  <complexType name="projects">
    <sequence minOccurs="1" maxOccurs="unbounded">
      <element name="project" type="tns:project"></element>
    </sequence>
    <attribute name="timeout" type="int" use="required"></attribute>
  </complexType>

  <complexType name="project">
    <attribute name="name" type="string" use="required"></attribute>
    <attribute name="site" type="string" use="required"></attribute>
  </complexType>
</schema>

=== EuPathDB-Infra/ApiCommonWebsite/Model/config/projects.sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- the timeout, in seconds, of a remote call to a project. -->
<projects timeout="0" xmlns="http://www.eupathdb.org" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.eupathdb.org ../lib/rng/projects.xsd ">
  <project name="EuPathDB" site="http://eupathdb.org/eupathdb/" />
  <project name="AmoebaDB" site="http://toxodb.org/toxo/" />
  <project name="CryptoDB" site="http://cryptodb.org/cryptodb/" />
  <project name="GiardiaDB" site="http://giardiadb.org/giardiadb/"></project>
  <project name="MicrosporidiaDB" site="http://microsporidiadb.org/micro/" />
  <project name="PiroplasmaDB" site="http://piroplasmadb.org/piro/" />
  <project name="PlasmoDB" site="http://plasmodb.org/plasmo/" />
  <project name="ToxoDB" site="http://toxodb.org/toxo/" />
  <project name="TrichDB" site="http://trichdb.org/trichdb/" />
  <project name="TriTrypDB" site="http://tritrypdb.org/tritrypdb/" />
</projects>
